version: '3.7'
services:
    front:
        container_name: front
        build: .
        command: sh -c "yarn --prefer-offline && yarn start"
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
        ports:
            - "3003:3003"